Adding NavBar
Kosjenka-Reading-App/Admin-Panel pull request #1
Opened 2023-11-04 19:17 UTC by Icon1cc

Created the NavBar as per figma UI. Please review it.

2023-11-05 18:18 UTC, DoStini requested changes

2023-11-05 18:18 UTC, DoStini commented on src/components/Sidebar.tsx
> +            style={{ backgroundColor: '#002D7E' }}
Don't use style to stle background colors, opt to tailwind CSS colors. You can see in @Satvik26 login's page how to use our pallete colors

2023-11-05 18:18 UTC, DoStini commented on src/components/Sidebar.tsx
> +                    <div className="bg-[#DEF2FF] rounded-lg w-12 h-12 flex items-center justify-center">
create predefined colors in the tailwind theme so we can use bg-primary or pg-secondary, etc

2023-11-05 18:18 UTC, DoStini commented on src/components/Sidebar.tsx
> +                        <span className="text-[#0099FF] text-3xl font-bold">K</span>
same here

2023-11-05 18:18 UTC, DoStini commented on src/components/Sidebar.tsx
> +                        className="bg-[#003EAE] p-0 rounded-lg flex items-center justify-center"
same here

2023-11-05 18:18 UTC, DoStini commented on src/components/Sidebar.tsx
> +                        className="bg-[#003EAE] p-0 rounded-lg flex items-center justify-center"
sam here

2023-11-06 16:28 UTC, Icon1cc commented
Updated the code as per Tailwind CSS as request. Please let me know if any further change is required. Thanks

2023-11-06 16:57 UTC, DoStini requested changes

2023-11-06 16:57 UTC, DoStini commented on src/components/Sidebar.tsx
> +                    </button>
After adding the new routes, use this component instead of a button https://reactrouter.com/en/main/components/link

2023-11-06 17:00 UTC, DoStini requested changes

2023-11-06 17:00 UTC, DoStini commented on src/components/Sidebar.tsx
> +                        <span className="text-blue-500 text-3xl font-bold">K</span>
Replace the text blue with our own colors

2023-11-11 23:25 UTC, DoStini approved these changes

2023-11-11 23:25 UTC, merged